export const businessTravelRows = [
  {
    id: 1,
    requestId: "FT2608001",
    requestDate: "14 Aug 2026",
    requestTime: "02:55 PM",
    displayName: "Mahesh Motilal Oswal",
    travelType: "Domestic",
    travelDate: "20 Aug 2026",
    poc: "Kiran Sawant",
    requestedBy: "kirans@vconstruct.com",
    status: "Approved",
    project: "Project Alpha",
    destination: "Dubai",
  },
    {
    id: 1,
    requestId: "FT2608001",
    requestDate: "14 Aug 2026",
    requestTime: "02:55 PM",
    displayName: "Mahesh Motilal Oswal",
    travelType: "International",
    travelDate: "20 Aug 2026",
    poc: "Kiran Sawant",
    requestedBy: "kirans@vconstruct.com",
    status: "Approved",
    project: "Project Alpha",
    destination: "Dubai",
  },
  {
    id: 2,
    requestId: "FT2611001",
    requestDate: "14 Aug 2026",
    requestTime: "02:41 PM",
    displayName: "Intequab Khan",
    travelType: "International",
    travelDate: "02 Nov 2026",
    poc: "Intequab Khan",
    requestedBy: "intequabk@vconstruct.com",
    status: "Pending",
    project: "Project Beta",
    destination: "Singapore",
  },
  {
    id: 3,
    requestId: "DT2608001M1",
    requestDate: "15 Jul 2026",
    requestTime: "04:58 PM",
    displayName: "Kiran Sawant",
    travelType: "Domestic",
    travelDate: "07 Aug 2026",
    poc: "Dipti Tipnis",
    requestedBy: "diptit@vconstruct.com",
    status: "Pending",
    project: "Project Gamma",
    destination: "Pune",
  },
  {
    id: 4,
    requestId: "DT2608001",
    requestDate: "15 Jul 2026",
    requestTime: "03:31 PM",
    displayName: "Dipti Tipnis",
    travelType: "Domestic",
    travelDate: "07 Aug 2026",
    poc: "Dipti Tipnis",
    requestedBy: "diptit@vconstruct.com",
    status: "Approved",
    project: "Project Delta",
    destination: "Mumbai",
  },
   {
    id: 4,
    requestId: "DT2608001",
    requestDate: "15 Jul 2026",
    requestTime: "03:31 PM",
    displayName: "Dipti Tipnis",
    travelType: "Domestic",
    travelDate: "07 Aug 2026",
    poc: "Dipti Tipnis",
    requestedBy: "diptit@vconstruct.com",
    status: "Approved",
    project: "Project Delta",
    destination: "Mumbai",
  },
   {
    id: 4,
    requestId: "DT2608001",
    requestDate: "15 Jul 2026",
    requestTime: "03:31 PM",
    displayName: "Dipti Tipnis",
    travelType: "Domestic",
    travelDate: "07 Aug 2026",
    poc: "Dipti Tipnis",
    requestedBy: "diptit@vconstruct.com",
    status: "Approved",
    project: "Project Delta",
    destination: "Mumbai",
  },
   {
    id: 4,
    requestId: "DT2608001",
    requestDate: "15 Jul 2026",
    requestTime: "03:31 PM",
    displayName: "Dipti Tipnis",
    travelType: "Domestic",
    travelDate: "07 Aug 2026",
    poc: "Dipti Tipnis",
    requestedBy: "diptit@vconstruct.com",
    status: "Approved",
    project: "Project Delta",
    destination: "Delhi",
  },
   {
    id: 4,
    requestId: "DT2608001",
    requestDate: "15 Jul 2026",
    requestTime: "03:31 PM",
    displayName: "Dipti Tipnis",
    travelType: "Domestic",
    travelDate: "07 Aug 2026",
    poc: "Dipti Tipnis",
    requestedBy: "diptit@vconstruct.com",
    status: "Approved",
    project: "Project Delta",
    destination: "Mumbai",
  },
   {
    id: 4,
    requestId: "DT2608001",
    requestDate: "15 Jul 2026",
    requestTime: "03:31 PM",
    displayName: "Dipti Tipnis",
    travelType: "Domestic",
    travelDate: "07 Aug 2026",
    poc: "Dipti Tipnis",
    requestedBy: "diptit@vconstruct.com",
    status: "Approved",
    project: "Project Delta",
    destination: "Mumbai",
  },
   {
    id: 4,
    requestId: "DT2608001",
    requestDate: "15 Jul 2026",
    requestTime: "03:31 PM",
    displayName: "Dipti Tipnis",
    travelType: "Domestic",
    travelDate: "07 Aug 2026",
    poc: "Dipti Tipnis",
    requestedBy: "diptit@vconstruct.com",
    status: "Approved",
    project: "Project Delta",
    destination: "Mumbai",
  },
   {
    id: 4,
    requestId: "DT2608001",
    requestDate: "15 Jul 2026",
    requestTime: "03:31 PM",
    displayName: "Dipti Tipnis",
    travelType: "Domestic",
    travelDate: "07 Aug 2026",
    poc: "Dipti Tipnis",
    requestedBy: "diptit@vconstruct.com",
    status: "Approved",
    project: "Project Delta",
    destination: "Mumbai",
  },
   {
    id: 4,
    requestId: "DT2608001",
    requestDate: "15 Jul 2026",
    requestTime: "03:31 PM",
    displayName: "Dipti Tipnis",
    travelType: "Domestic",
    travelDate: "07 Aug 2026",
    poc: "Dipti Tipnis",
    requestedBy: "diptit@vconstruct.com",
    status: "Approved",
    project: "Project Delta",
    destination: "Mumbai",
  },
   {
    id: 4,
    requestId: "DT2608001",
    requestDate: "15 Jul 2026",
    requestTime: "03:31 PM",
    displayName: "Dipti Tipnis",
    travelType: "Domestic",
    travelDate: "07 Aug 2026",
    poc: "Dipti Tipnis",
    requestedBy: "diptit@vconstruct.com",
    status: "Approved",
    project: "Project Delta",
    destination: "Mumbai",
  },
   {
    id: 4,
    requestId: "DT2608001",
    requestDate: "15 Jul 2026",
    requestTime: "03:31 PM",
    displayName: "Dipti Tipnis",
    travelType: "International",
    travelDate: "07 Aug 2026",
    poc: "Dipti Tipnis",
    requestedBy: "diptit@vconstruct.com",
    status: "Approved",
    project: "Project Delta",
    destination: "Mumbai",
  },
];